Makefile, cmd/ygg/main.go, cmd/yggd/main.go, internal/util.go
Add two hidden flags, `--generate-man-page` and `--generate-markdown`, to `ygg` and `yggd`. They produce man pages and a general markdown "USAGE" file for documentation. Also add a bash completion function to produce bash completion hints.
=> Generate man pages and bash completion

cmd/yggd/main.go
A new --topic-prefix option enables the default topic prefix to be overridden at run time. This value can be set either in the config file or via the command-line option. This option really only exists for QE, so it's hidden and undocumented intentionally.
=> Add hidden --topic-prefix option

.gitignore
Prevent accidentally commiting build output files.
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
=> fix: Add make output to gitignore

README.md
Fix the subcommand name in README.md for starting the registration
procedure from register to connect.
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
=> fix: Fix subcommand name for register/connect

cmd/ygg/main.go
The URL in the connect description was missing the 'e', and all the
links to red.ht/connector were using the http protocol instead of https.
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
=> fix: Fix connector urls

Makefile, cmd/yggd/main.go, constants.go, data_processor.go, yggdrasil.spec.rpkg
If set to a non-empty string, the data-host config option will force all HTTP traffic sent by the `DataProcessor` through the specified host. When `DataProcessor` is processing a message, if the worker has `detachedContent` set to `true`, the value of the message's `content` field is parsed as a URL and the value of the URL's `Host` field is set to the value specified by the data-host argument before sending the HTTP request to the HTTP client for handling.
If no value is set in either the config file or on the command line, a compile-time constant, `DataHost` is set as the default value. In any case, if the value of `DataHost` is an empty string, no host substitution is performed.
Fixes RHCLOUD-12548
=> feat: New config option: data-host

cmd/yggd/main.go, data_processor.go, dispatcher.go, go.mod, go.sum
When a message is dispatched to a worker, it is deleted from the internal memory store. When data is received from a worker, rather than looking up the original message to identify the worker that sent it, the new message is added to the memory store. The DataProcessor then attempts to parse the directive as a URL; if that succeeds (where "succeeds" in this case means the parsed value includes a valid URL scheme component), the message/worker is treated as a detachedContent worker and the data is return via HTTP.
Fixes RHCLOUD-12336
=> fix: delete messages after dispatch

.copr/Makefile, .gitignore, yggdrasil.spec.in
The `rpkg` build source type worked for a quick, initial integration with COPR to build RPMs. I want more control over how the version and release values get set during COPR builds, so this PR removes the `rpkg` template, and instead uses COPR's `make srpm` method of generating a source RPM.
=> Support custom "srpm" builds in COPR

canonical_facts.go
Signed-off-by: Adam Miller <admiller@redhat.com>
=> BIOSUUID can be the empty string if sysfs doesn't provide one

cmd/yggd/main.go, cmd/yggd/tls.go, cmd/yggd/util.go
There are 3 new functions that perform operations on a client ID file:
1. `createClientID` will generate a semi-random string and set the contents of the client-id file to that string.
2. `getClientID` simply reads the contents of the file.
3. `setClientID` writes a value it is given to the file.
These 3 functions are using during the main program execution to determine a client ID value. The logic is as follows:
If a "cert-file" option is given, the certificate is parsed for a CN value. That value is then written to the client-id file. The client-id file is then read. If the contents of the read file is empty, a client-id is generated via `createClientID`. The global `ClientID` variable is then set to the value either read from the client-id file or generated if the value was empty.
The …
=> feat(yggd): decouple MQTT client ID from certificate CN

cmd/yggd/mqtt.go, cmd/yggd/tags.go
Change the tag parsing function to log an error, but continue to publish
the connection-status message with an empty tags map instead.
Fixes: ESSNTL-994
Fixes: ESSNTL-1128
=> fix: make malformed tags content not fatal

.github/workflows/go.yml, Makefile
This patch adds multiple GitHub Workflow Actions:
* Run go build, go test and go vet
Signed-off-by: Gael Chamoulaud (Strider) <gchamoul@redhat.com>
=> ci: Add Github Workflow Actions

cmd/yggd/util.go
k4e needs the generated client ID to be a valid kubernetes name and capital letters that might appear in the suffix generated by `randomString(8)` are not allowed. 
Proposed fix uses UUID as a suffix, which should provide both better entropy and compliance with k8s naming requirements.
=> Using UUID for generated ClientID

cmd/yggd/main.go
This PR adds couple of environment variables that are passed to the workers:
- `BASE_CONFIG_DIR` - yggdrasil configuration directory, within which the workers can create their own configuration subdirectory;
- `LOG_LEVEL` - forwarding yggdrasil's log level to be applied by the workers;
- `DEVICE_ID` - ID of the device as used by yggdrasil; to give workers possibility to use device identity in their logic.
=> Additional environment variables

yggdrasil.spec.in
https://github.com/RedHatInsights/yggdrasil/commit/ffb580f55ae91beff78156fdb6a41be8bc049117 removed ygg from the source code, but it remained referenced by the spec file. This PR removes that reference to allow the RPM to be built without errors.
=> fix(build): removed yggdrasil reference from the spec template

cmd/yggctl/generate.go, cmd/yggctl/generate_test.go, cmd/yggctl/main.go, messages.go
Previously, the yggctl generate commands relied on some quick marshalling and unmarshalling of map[string]interface{} types. This led to some bugs when trying to get JSON into the `content` field of messages. This PR updates the message generation logic to first create full yggdrasil message types, correctly populate the fields, and then marshal them into JSON before printing the message to standard output.
=> Improve the yggctl generate commands

Makefile
This patch replaces 'PACKAGE' by 'PKGNAME' in the Makefile.
Signed-off-by: Gael Chamoulaud (Strider) <gchamoul@redhat.com>
=> fix: Fixes an Undefined variable 'PACKAGE' warning

cmd/yggd/exec.go, cmd/yggd/main.go
Add a `--exclude-worker` command flag and configuration parameter. Any strings listed in this argument will be stored in an exclusion list at run time. If a worker's *basename* matches a string in this list, it is excluded from execution when starting worker processes. For example, `--exclude-worker echo-worker` will prevent the file `/usr/libexec/yggdrasil/echo-worker` from being executed.
Fixes: #44
=> Backport-exclude-workers

.github/workflows/go.yml, Makefile
ci: Add Github Workflow Actions
This patch adds multiple GitHub Workflow Actions:
* Run go build, go test and go vet
Signed-off-by: Gael Chamoulaud (Strider) <gchamoul@redhat.com>
(cherry picked from commit a0bad21c841faeae23ff4a084bb56c2ce18c2ab7)
=> Backport-github-workflow-actions

README.md, cmd/yggd/client.go, cmd/yggd/exec.go, cmd/yggd/exec_test.go, cmd/yggd/grpc.go, cmd/yggd/main.go, cmd/yggd/registry.go, cmd/yggd/registry_test.go, cmd/yggd/worker.go, cmd/yggd/worker_test.go, go.mod, worker/echo/echo.toml
This PR refactors the way processes are started, watched, killed, and restarted. The routines in `exec.go` were a mixture of higher-level worker process management (including restart delays, PID file management, etc.) and lower-level process start and kill routines. This PR moves the higher-level logic out of `exec.go` and into a file called `worker.go`. The routines in `exec.go` are now purely lower-level routines that start and stop processes; they have no awareness of worker configuration or process restart management (`startProcess`, `stopProcess`, `waitProcess`). The functions in `worker.go` operate on a `workerConfig` data structure to start, stop and manage workers.
A `workerConfig` structure is created by parsing a configuration file that must be defined in …
=> Start workers explicitly

cmd/yggd/config.go, cmd/yggd/main.go, constants.go, internal/transport/http.go, internal/transport/mqtt.go
Currently yggd supports MQTT prefix, in this way adds a prefix to the
MQTT topic. This commit adds the same feature for HTTP, so adds the
prefix to the http endpoint.
Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>
=> feat: HTTP transport add prefix

Makefile, yggdrasil.spec.in
If LDFLAGS is set in the environment before building, the flags in the
variable will get integrated into the LDFLAGS passed to the compiler.
This enables building with environment-dependent flags.
This is actually an upstreaming of a patch applied downstream in RHEL.
Resolves: RHBZ#2023489
=> respect LDFLAG value from the environment

Makefile, cmd/yggd/main.go
Assumptions are made by yggd 0.2.x that content will be available in the cert-file and key-file contents. When run without values for these flags, errors occur.
=> Make cert-file and key-file required

internal/http/client.go
When the body is empty the ReadAll initialised a empty array with cap of
512, so when try to Marshal to Json will fail, this check that has
content.
Issue example:
```
package main
import (
"encoding/json"
"fmt"
)
type Response struct {
// StatusCode response
StatusCode int
// Response Body
Body json.RawMessage
// Mestadata added by the transport, in case of http are the headers
Metadata map[string]string
}
func test(data *Response) {
res, err := json.Marshal(data)
fmt.Println("Err: ", err)
fmt.Printf("Data:%s\n", res)
fmt.Println("---------------------------------")
}
func main() {
fmt.Println("Test 1")
test(&Response{StatusCode: 200, Body: []byte{}, Metadata: map[string]string{"foo": "bar"}})
fmt.Println("Test 2")
test(&Response{StatusCode: 200, Body: nil, Metadata: …
```
=> fix: don't parse json.rawmessage if body if empty

internal/transport/http.go, internal/transport/http_test.go
I discovered that when the HTTP response is >400 the error is not nil,
and the transport didn't return the http.Response back to the worker.
With this commit, in case of the transport.Send fails, it returns an
error and also the http response to the worker that requested it.
Discovered on: https://github.com/project-flotta/flotta-operator/pull/144
Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>
=> fix: HTTP Transport return all responses

.copr/Makefile
With the new release of fedora/centos9, some issues with Git regarding
safe-directories.
Fedora-copr clone the repo as mockbuild user, and when doing git rev
list failed with the following message.
```
fatal: unsafe repository ('/mnt/workdir-mupe3qpk/yggdrasil' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /mnt/workdir-mupe3qpk/yggdrasil
```
Tried with safe-directories, but results didn't work as expected, so
chown the code to the right user was the best thing in this case.
Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>
=> Fix: change permissions on make srpm

cmd/yggd/config.go, cmd/yggd/main.go
Add a new config file value and command-line flag: --worker-config-dir.
Setting this flag to a directory path will instruct yggd to look for
worker config files in that directory. The default value is
SYSCONFDIR/yggdrasil/workers, to remain compatible with the previous
implementation.
=> Configurable worker config directory

Makefile
* When make is used for building yggdrasil, then gzip is triggered to compress man page, but it required confirmation that old compressed man page would be rewritten. Adding -f option avoid the need of this confirmation.
* Original PR for rhc: https://github.com/RedHatInsights/rhc/pull/19
=> fix: Simple fix of Makefile to not require user input

cmd/yggd/exec.go
Some workers output a lot of text to stderr and stdout. Rather than
scanning stderr and stdout into a buffer using a bufio.Scanner, read a
fixed number of bytes at a time. This will break lines of output from
the worker in the middle of words, making reading stdout in the logs
more difficult, but avoids the overly verbose workers from hitting the
bufio.ErrTooLong error.
=> Read worker output using io.Read

cmd/yggd/main.go, internal/config/config.go
Remove exclude-workers and worker-config-dir options. Both are no longer
used due to the removal of worker process management.
Fixes: #106 
Fixes: #107
=> fix: remove unused config options

cmd/yggd/main.go, data/yggdrasil/config.toml, internal/config/config.go, internal/transport/mqtt.go
The MQTT transport supports the notion of multiple brokers; while the
HTTP transport does not, we can still support both by converting the
--server flag into a string slice. The HTTP transport is created with
only the first element of the string slice flag, while the MQTT
transport accepts the entire slice. Each broker in the slice is added
during the connection process of the MQTT transport.
Fixes: #80
=> feat: multiple brokers

.github/workflows/go.yml, .github/workflows/lint.yml
Update github action versions to avoid the deprecated node12 actions.
=> Update action versions

cmd/yggctl/actions.go, cmd/yggctl/main.go
The purpose of this refactor is to follow better design patterns as suggested by Jiri
and move the yggctl anonymous action functions into non-anonymous functions 
defined in a separate file to prevent polluting the yggctl main file.
=> refactor: yggctl actions into non-anonymous functions

CONTRIBUTING.md
* Fixed one issue with example
* Added instruction how to start mosquitto server
* Replaced test.mosquito.org with localhost, because it is really easy to run mosquitto server
* Wrapped too long lines
* Added some notes
=> Improved CONTRIBUTING.md file

data/dbus/yggd.conf, data/systemd/meson.build, meson.build, worker/echo/com.redhat.Yggdrasil1.Worker1.echo.conf, worker/echo/com.redhat.Yggdrasil1.Worker1.echo.service.in, worker/echo/meson.build
Remove the use of the send_destination_prefix attribute from yggd's
busconfig policy. Instead, each worker must install their own busconfig
policy. Update the echo worker to demonstrate this.
=> Remove send_destination_prefix

cmd/yggctl/actions.go, cmd/yggd/client.go, dbus/com.redhat.Yggdrasil1.xml, internal/work/dispatcher.go, ipc/com.redhat.Yggdrasil1.Worker1.xml, ipc/interfaces.go, worker/echo/main.go, worker/worker.go
The purpose of this update is to prepare for the implementation of a 
message journal in yggdrasil by making small changes to workers.
This change adds the worker's message id to the emitted event data in addition 
to the currently existing ipc worker event name and worker message data.
**Current:** `...EmitEvent(worker_event_name, worker_event_message)`
**Proposed:** `...EmitEvent(worker_event_name, worker_event_message, worker_message_id)`
Changes:
- updated dbus interfaces to include new message id field.
- updated "listen" yggctl action to include new message ids.
- updated "WorkerEvent" dbus signals to include new message ids.
=> feat: include message id in emitted worker events

internal/transport/http.go, internal/transport/mqtt.go
Some debug and trace logs were printing message content after being downloaded by the DetachedContent option.
This commit removes some of those logs that will prevent important information being leaked.
=> feat: Remove debug and trace content log

.copr/Makefile, .github/workflows/package.yml, CONTRIBUTING.md, dist/meson.build, dist/srpm/README.md, dist/srpm/meson.build, dist/srpm/yggdrasil.spec.in, meson.build, meson_options.txt
I added a 'dist' subdirectory, for distributions to maintain in-tree distribution compilation instructions. I added an 'srpm' subdirectory that uses meson's `run_target` to build an SRPM. The source tarball inserted into the SRPM is created from the *working* source root directory, including uncommitted changes. The resulting SRPM will include git version information in its "Release" field. The SRPM can be found in the meson build root, under the 'dist/srpm' directory.
Using that custom 'srpm' target, I added a `.copr/Makefile` that supports the COPR "make srpm" strategy to building packages. This enables the existing webhook to trigger [builds in COPR](https://copr.fedorainfracloud.org/coprs/linkdupont/yggdrasil/builds/).
Additionally, using that custom 'srpm' target, I added a GitHub …
=> Enable CI builds

cmd/yggd/main.go
Add three options to adjust MQTT client configuration:
- mqtt-connect-retry
- mqtt-connect-retry-interval
- mqtt-auto-reconnect
We are exposing these options as hidden configurable values in the hope that we can identify a cause for some unknown client disconnections.
=> feat: add MQTT connection options

.github/workflows/lint.yml
golangci-lint CI actions are failing due to the lower default timeout (1m), and this commit
updates the yaml to include a 3m timeout: `--timeout=3m`
This should resolve CI issues popping up in: https://github.com/RedHatInsights/yggdrasil/pull/116
=> fix(ci): golangci-lint timing out in large PRs

cmd/yggctl/actions.go
yggctl will attempt to connect to the session bus only if
DBUS_SESSION_BUS_ADDRESS is non-empty and the effective UID of the
process is greater than zero. This results in root invocations of yggctl
preferring the system bus over the session bus.
Fixes: #142
=> fix(yggctl): prefer system bus when run as root

README.md
Correct the godocs.io badge URL to the import path of the module.
=> Correct godocs.io import path

cmd/yggd/main.go, dist/srpm/yggdrasil.spec.in, internal/transport/noop.go
Add a noop transport option. Setting the config flag 'protocol' to
"noop" or "" will configure yggd with a no-op transport. All the rest of
the dispatch and routing flows are unaffected, but no data is
transported to or from the client.
=> Add 'noop' transport

CONTRIBUTING.md, cmd/yggctl/actions.go, cmd/yggctl/main.go
Update the generate data-message and generate control-message
subcommands to read message content from a file path passed as the first
positional argument on the commandline. Support the convention reading
from stdin if the file path is '-'.
=> feat(yggctl): Read content from files or stdin

internal/work/dispatcher.go, internal/work/dispatcher_test.go, internal/work/errors.go
Return errors when handling Event signals emitted by workers and handle
the optional 'message' parameter gracefully.
=> fix: handle Event signals gracefully

.github/workflows/lint.yml, CONTRIBUTING.md
This PR adds golines checking to new PRs and prevents merging to main if it detects that the code has not been formatted for golines.
**Note:**
Not sure if there's a better way to do this, but If there's a way to automatically run golines on every PR during merging instead of requiring commits to comply to golines formatting then that might be a better solution. Of course that could introduce a potential for errors caused by golines to be merged into main so I'm not sure.
=> ci: added golines lint checking

cmd/yggctl/actions.go, cmd/yggd/client.go, dbus/com.redhat.Yggdrasil1.xml, internal/work/dispatcher.go, internal/work/dispatcher_test.go, internal/work/errors.go, ipc/com.redhat.Yggdrasil1.Worker1.xml, ipc/interfaces.go, worker/echo/main.go, worker/worker.go
This commit is proposing a change in how optional data is sent in emitted events
and parsed in the yggdrasil dispatcher to simplify the process if additional optional
data needs to be included in emitted worker events in the future.
This update should also not show any changes in behaviour compared to the main branch.
This work primarily came out of attempts to add a `responseTo` optional field in the emitted event
while avoiding parsing complications in the dispatcher. [#141]
=> feat: reworked optional data sent in emitted events

.github/workflows/go.yml, .github/workflows/package.yml, meson.build
The `main` branch currently contains [changes](https://github.com/RedHatInsights/yggdrasil/commit/5f12e93f9edf552e3a1b1a2d77b10185620d78c0) that will break clients expecting the D-Bus protocol that shipped with 0.3.2. While yggdrasil is still "not 1.0", I am trying to maintain as little API breakage as possible. Marking the next version as 0.4.0 hopefully signifies more explicitly that this version is different than previous versions. Clients will need to be updated in order to communicate with yggdrasil 0.4.0.
=> Set version to 0.4.0

cmd/yggctl/actions.go, cmd/yggd/client.go, dbus/com.redhat.Yggdrasil1.xml, internal/work/dispatcher.go, internal/work/dispatcher_test.go, ipc/com.redhat.Yggdrasil1.Worker1.xml, ipc/interfaces.go, worker/echo/main.go, worker/worker.go
Currently uses cherry-picked commits from dependent PR: #140 which needs to be removed when the dependent PR gets approved and merged.
=> feat: added "responseTo" field in worker emitted events

.github/workflows/package.yml
Include 'systemd' in the list of packages required to run the `build-srpm` job.
=> Include 'systemd' in build-require packages

cmd/yggd/main.go, internal/config/config.go, internal/transport/mqtt.go
Add a new hidden flag: --mqtt-reconnect-delay. This flag will sleep for the given duration before attempting to reconnect to the MQTT broker. This only works if --mqtt-auto-reconnect is enabled (it is true by default).
I also noticed that the previously added MQTT flags were not set into the DefaultConfig struct, so their values when read from the struct were always the zero value. I fixed this in a separate commit on this same PR.
=> Add a delay before reconnecting to MQTT

cmd/yggd/main.go, internal/config/config.go, internal/transport/mqtt.go
When connecting to a broker and when publishing a message, use the
`Token.WaitTimeout` method instead of `Token.Wait`. `Token.Wait` waits
indefinitely, which can lead to situations when the client never
succeeds in connecting or publishing.
The timeout for each operation can be configured independently by
setting `mqtt-connect-timeout` and `mqtt-publish-timeout`. Both values
default to 30 seconds. The flags are hidden, as they should not commonly
be required to be changed by users.
=> feat(mqtt): Use Token.WaitTimeout

cmd/yggd/client.go, internal/work/dispatcher.go, ipc/com.redhat.Yggdrasil1.Worker1.xml, messages.go, worker/echo/main.go, worker/worker.go
Add a new control message of type command that can be used to cancel a work that is already in progress in a worker. 
`yggd` will receive this command and forward it to the appropriate worker. If this worker implements the cancellation feature it will stop or cancel its work. But it is up to the worker to implement this functionality. 
This PR also provides an example of how the cancellation message can be implemented in the `echo worker`. It uses a map of synchronized channels to manage the current work, and to send the cancellation message to the `goroutines` that are handle it. 
- A new command  message that can be use to cancel work in progress that is done in the workers.Is send as a command to yggdrasil client. Yggdrasil will send this message to the workers Cancel method.
- A new …
=> Added new command message: Cancel

doc/diagrams/yggd-cancel-command.mmd, doc/diagrams/yggd-connection.mmd, doc/diagrams/yggd-data.mmd
Added this directory to tack the protocol diagrams. 
Initial diagrams added
- Connection
- Data message Echo worker
- Cancel message Echo worker
Github provides a pre-view of mermaid diagrams. To see it go to the forked repo https://github.com/ahitacat/yggdrasil/tree/doc-init-diagrams/doc/diagrams
=> docs: Added a diagram directory

dist/srpm/meson.build, dist/srpm/yggdrasil.spec.in
This tweaks the available RPM packaging so it can be used also on EL 8; high-level summary of the changes:
- the Go (S)RPM macros are used only if available, falling back to other macros or setting fallback variables to reduce differences
- generate an upstream tarball compatible with what older RPM versions expect
See the messages of each commit for longer explanations.
=> Packaging fixes

.github/workflows/package.yml
* The building of package was not trigger, when PR was opened.
This commit fixes this issue
=> fix: build RPM packages as part of our CI 

internal/work/dispatcher.go, ipc/com.redhat.Yggdrasil1.Worker1.xml, ipc/interfaces.go, worker/worker.go
* When worker is started, then it sends event "started"
* It also sends event "stopped", when it is terminated and process cannot handle message anymore
* This functionality is IMHO important for developers of yggdrasil worker. When you develop new worker it is important to see that your worker "communication" with yggd during start. It is also decency to say something like "good bye" at the end.
* Small refactoring of code (do not use numeric constant)
* Updated doc strings
* Extended documentation in `com.redhat.Yggdrasil1.Worker1.xml`
according changes in code
=> feat: Add more events for starting and stopping of worker

.copr/Makefile
Only the basic `git` tool is needed, so avoid pulling the extra bits (e.g. Perl) when building the SRPM in Copr.
=> build: install git-core insted of git

cmd/yggd/main.go, cmd/yggd/mqtt.go
This is a backport of #165 to yggdrasil-0.2.
When connecting to a broker and publishing a message, use the
`Token.WaitTimeout` method instead of `Token.Wait`. `Token.Wait` waits
indefinitely, which can lead to situations when the cleint never
succeeds in connecting or publishing.
The timeout for each operation can be configured independently by
setting `mqtt-connect-timeout` and `mqtt-publish-timeout`. Both values
default to 30 seconds. The flags are hidden, as they should not commonly
be required to be changed by users.
Fixes: CCT-123
=> Use Token.WaitTimeout

CONTRIBUTING.md, messages.go
When encoding a data message, the content should remain unmodified. When it is typed as a `[]byte`, it ends up getting encoded in base64. Typing it as `json.RawMessage` ensures the content is unmodified when marshaled into JSON.
=> Encode data message content as raw JSON

internal/work/dispatcher.go
* When worker was in remote content mode, then yggdrasil still expects raw data as valid JSON document. URL like: http://example.com/ is not valid JSON document. It could be e.g. "http://example.com/"
* Not sure if this is the best solution, but it solves the issue described in issue #208
=> fix: Fixed dispatching of URL for worker in remote content mode

Makefile
Drop 'go mod tidy' from the 'clean' Makefile target.
=> build: remove 'go mod tidy'

README.md, cmd/yggd/exec.go, cmd/yggd/exec_test.go, cmd/yggd/main.go, cmd/yggd/util.go, cmd/yggd/worker.go, cmd/yggd/worker_test.go
This PR refactors the way processes are started, watched, killed, and restarted. The routines in `exec.go` were a mixture of higher-level worker process management (including restart delays, PID file management, etc.) and lower-level process start and kill routines. This PR moves the higher-level logic out of `exec.go` and into a file called `worker.go`. The routines in `exec.go` are now purely lower-level routines that start and stop processes; they have no awareness of worker configuration or process restart management (`startProcess`, `stopProcess`, `waitProcess`). The functions in `worker.go` operate on a `workerConfig` data structure to start, stop and manage workers.
A `workerConfig` structure is created by parsing an optional configuration file that must be defined in …
=> Configurable worker environment variables

.packit.yaml
Specify the list of targets to build in the 'main' COPR job. Hopefully this eliminates the behavior of Packit creating a separate COPR build for each buildroot/architecture pair in the project's enabled buildroots.
=> Specify targets in main-branch job

README.md
Update the README to clarify the expected worker configuration file name.
=> Clarify worker configuration file name

cmd/yggd/worker.go, worker/echo/main.go
Set the log level according to the value of YGG_LOG_LEVEL.
Print the worker's environment when run at level Debug or higher.
=> feat(echo): set log level according to env

cmd/yggd/client.go, cmd/yggd/main.go, internal/config/config.go
The notion of "canonical facts" is unique to Red Hat Insights. However,
the idea of transmitting a set of facts about a system upon connection
is generic enough that it can still exist as an option in yggd. This
commit renames the "canonical-facts" flag, config value and related
variables to "facts-file" to more accurate reflect what it expects (a
file) and to be generic enough to accept any set of "facts" about the
system.
Notably, this commit *does not* rename the "canonical_facts" JSON field
in the "connection-status" message; that field name is part of the
agreed JSON schema in the message protocol, so changing that field would
require breaking the protocol. The protocol does have a mechanism for
such a situation; the "version" field of a message can be incremented.
However, for now, …
=> Rename "canonical-facts" flag

cmd/yggd/client.go, internal/work/dbus.go, internal/work/dbus_test.go, internal/work/dispatcher.go
The D-Bus name specification does not allow hyphens (-) in names or paths. Workers should really switch to using compliant names. However, in order to maintain compatibility with existing services, when a message is received for a worker, the name is passed through a scrubbing function that cleans up the name. As of this PR, this scrub function replaces hyphens with underscores and returns an error. This error is then logged. These log messages should hopefully encourage service authors to switch to using compatible names.
Closes: #210
=> Allow hyphenated names, with a warning

.github/workflows/dist.yml
With this workflow, when a new git tag is created using the semantic versioning syntax (vX.Y.Z), this workflow checkout the tag from git, generates a `yggdrasil-X.Y.Z.tar.xz` and attaches it as an asset to the release.
[Here's an example](https://github.com/subpop/yggdrasil/actions/runs/9197368705/job/25297639408) of the workflow running on my fork.
=> Add dist workflow

internal/work/dispatcher.go, worker/worker.go
* Improved messaging in various cases (mostly related to D-Bus methods and signals)
* All changes comes from closed PR #157 (running yggdrasil as non-root user)
=> feat: Improve error and debug messaging

worker/echo/dbus/com.redhat.Yggdrasil1.Worker1.echo.conf.in, worker/echo/dbus/com.redhat.Yggdrasil1.Worker1.echo.service.in
The recent changes to allow `yggd` and workers to run as non-root users involved making change to the D-Bus access policies. The D-Bus policy for the echo worker installed a policy that only permitted the user "yggdrasil-worker" to send messages on the bus. This created an issue where `yggd` could not send messages to the echo worker.
Optionally increase the `log-level` in `/etc/yggdrasil/config.toml` to a higher value if you want to observe more logging output. Using a network transport for message dispatch is not necessary to reproduce this, so you can optionally disable the network transport by setting `protocol` to `"none"`.
1. Start `yggd`: `sudo systemctl start yggdrasil`
2. In a second terminal, run `sudo yggctl listen -w echo` to observe whether the message is received
3. Send a …
=> Correct echo worker D-Bus policy permissions

.packit.yaml
Include CentOS Stream 10 buildroots in COPR. Additionally, explicitly build both x86_64 and aarch64 packages.
=> Include CentOS Stream 10 when building with packit

cmd/yggctl/actions.go, cmd/yggctl/main.go, cmd/yggctl/templates.go, internal/constants/constants.go, meson.build
The generate worker-data command creates files relevant to D-Bus and systemd in order for a worker to communicate with yggd. This is intended to make worker development easier; if a worker has a relatively standard startup and policy configuration, it can be configured to invoke this subcommand instead of keeping the files in its own source repository.
The files can either be installed directly by specifying the --install flag, or they can be written to a given output directory.
The --user, --program and --name flags must be included in the invocation. For example:
```
yggctl generate worker-data \
--name echo \
--program /usr/libexec/yggdrasil/echo \
--user $(pkgconf yggdrasil --variable worker_user \
--install
```
Card ID: CCT-680
=> feat(yggctl): add generate worker-data command

data/systemd/system/yggdrasil.service.in
Older versions of yggdrasil shipped a service named yggd.service. Adding
an alias directive with this value eases
the migration/upgrading from older versions of yggdrasil.
=> fix(systemd): add Alias for yggd.service

cmd/yggctl/actions.go, cmd/yggctl/main.go, cmd/yggd/util.go, internal/work/dispatcher.go
The current implementation of `yggd` could be described as "lazy discovery of workers"; a worker is only discovered when a message arrives destined for it and the message is routed. If and only if `yggd` is able to successfully deliver a message to a worker, is it then added to the dispatchers table, triggering a publish of an updated "connection-status" message. This lazy-loading causes `yggctl` to output incorrect worker status under certain conditions. If `yggctl workers list` is run immediately after starting `yggd`, the list will be empty.
This PR changes the procedure `yggd` uses to detect and collect workers. After connecting to the bus (in the `(Dispatcher).Connect` method), a goroutine is run that scans the list of names on the bus, collecting any that begin with …
=> Collect workers immediately

internal/work/dispatcher.go
When publishing the dispatchers table, include both underscore names and classic hyphenated names. This cannot cause any conflict with existing/local workers since hyphens in worker names is disallowed by the D-Bus name policy.
Card ID: RHEL-58762
=> Include hyphenated worker names

dist/srpm/yggdrasil.sysuser.in
* System user yggdrasil (@user@) is added to supplementary group rhsm. This allows yggdrasil running as non-root user read consumer certificate and key (/etc/pki/consumer/*.pem).
* When `rhsm` group does not exists, then it is automatically created.
=> feat: Add yggdrasil user to supplementary group rhsm

internal/http/client.go
Log the responses received from HTTP requests made by the built-in client. These responses are probably large, so they're logged at the debug level.
=> Log HTTP response from client requests

.packit.yaml
* Centos stream 8 is not supported anymore. No need to have it in our CI
=> fix: Remove centos-stream-8 from CI

.packit.yaml, dist/srpm/yggdrasil.spec.in
The bash-completion package split the pkgconfig file into a -devel
subpackage in f41. Update the build dependency to use pkgconfig() rather
than explicitly by name.
=> ci: fix srpm build failures on f41 buildroots

dist/srpm/yggdrasil.spec.in
This PR fixes the NVR of resulting COPR builds so they include SCM information and can resolve as newer than upstream distribution packages when installing them.
=> Fix NVR in COPR builds

dist/srpm/yggdrasil.spec.in
Include the local state dir in the RPM so that the directory is created
when the package is installed. This enables other services that want to
write to the directory before the yggdrasil service starts.
=> build(rpm): Include local state dir

go.mod, go.sum
Card: CCT-896
The bundled version of go-yaml in yggdrasil-0.2 has a known security flaw. This PR will update yggdrasil-0.2 release branch to include version 2.2.4 of go-yaml to address the CVE
=> fix: Update bundled version of go-yaml to v2.2.4

.packit.yaml, dist/srpm/yggdrasil.spec.in
Adjust the forge macros so they work across EL9, 10 and Fedora.
=> fix: adjust release to include git info

dist/srpm/yggdrasil.spec.in
The workaround for %dist being empty in a COPR SRPM build was
inadvertently removed during a previous refactoring of the spec file.
=> build(rpm): Reintroduce %dist fix

.github/workflows/update-version.yml, cmd/yggctl/actions.go
Include 'bash-completion' in the list of build dependencies when installing them during 'update-version'.
Card ID: CCT-1089
=> ci: add bash-completion to build deps

internal/work/dispatcher.go
When the Dispatcher connects, find all activatable workers instead of only active/running workers. This will include workers that are installed but that have not yet started.
Card ID: CCT-862
=> List Activatable Workers on startup

.github/workflows/tag-release.yml
Install bash-completion during tag-release workflow
=> Include bash-completion in build dependencies

internal/work/dbus.go
* When MQTT message with old directive standard is received, then do not print scary message, but only print informative message that name was transformed
* Added one more unit test
=> fix: Do not print scary messages to log for old directive

.packit.yaml
The `@yggdrasil/latest` copr is used to build yggdrasil/main, and only for newer versions of RHEL. Since this branch only builds for RHEL 8 & 9 currently, then let's amend the packit configuration to build in the right place:
- split the jobs for PRs and commit depending on the RHEL version, as they will need to use different copr's
- use the right copr's depending on the version built
- use unique identifier to avoid conflicts
=> [0.2] ci: fix packit configuration for versions & coprs

.packit.yaml
Specify the right branch of this branch, so packit triggers the build correctly.
Fixes commit aa62e381658d72051fec00382fa39288b0c2045a.
=> ci: fix packit config for post-merge builds

CONTRIBUTING.md, README.md, cmd/yggd/main.go, data/yggdrasil/config.toml, dist/srpm/yggdrasil.spec.in, internal/config/config.go
**Card:** CCT-648
This PR supports delivering yggd with fully commented out config file.
and
The hardcoded, default, broker protocol is being changed from mqtt to none.
**_See file(s):_**
-   modified:   internal/config/config.go
A small comment change was made to include the supported values for the broker protocol.
**_See file(s):_**
-   modified:   CONTRIBUTING.md
-   modified:   README.md
The CONTRIBUTING and README pages were updated to reflect the functional changes.
**_See file(s):_**
-   modified:   cmd/yggd/main.go
The hardcoded, default, broker protocol is changed from mqtt to none.
**_See file(s):_**
-   modified: data/yggdrasil/config.toml
The file /etc/yggdrasil/config.toml now contains all commented out lines.
**_See file(s):_**
-   modified:   dist/srpm/yggdrasil.spec.in …
=> feat: Support an empty config file

.github/workflows/go.yml, .github/workflows/lint.yml, .packit.yaml, Makefile, cmd/yggd/exec.go, cmd/yggd/worker.go
When stopping a process, there is a chance the OS has already stopped the process. In that case, `Process.Kill` returns `os.ErrProcessDone`. This should not be considered a fatal error. This PR handles that case and does not return an error from `stopProcess` if the underlying `Process.Kill` call returns `os.ErrProcessDone`.
There are steps to reproduce this issue in #96, as well as [CCT-1066](https://issues.redhat.com/browse/CCT-1066).
I reproduced it by following steps 1 through 5 in CCT-1066, and then augmenting the running version of rhcd with one from the repository. There are steps in a comment in CCT-1066 that describe this process.
```
sudo go run -ldflags '-X github.com/redhatinsights/yggdrasil.PrefixDir=/usr -X github.com/redhatinsights/yggdrasil.LocalstateDir=/var -X …
```
=> Avoid fatal error on ErrProcessDone

dist/srpm/yggdrasil.spec.in
Card ID: CCT-1228
This changes will create the symlink  /usr/lib/systemd/system/rhcd.service pointing to  /usr/lib/systemd/system/yggdrasil.service
To test this, after the COPR rpm is installed the following ls command should show the sym link
For example:
```
$ ls -aFl /usr/lib/systemd/system/rhcd.service
lrwxrwxrwx. 1 root root 41 Mar 10 14:10 /usr/lib/systemd/system/rhcd.service -> /usr/lib/systemd/system/yggdrasil.service
```
=> fix: Create rhcd.service sym link to yggdrasil.service

.packit.yaml
* Try to fix issue with downloading required go modules during build process. The network is disabled by default.
* Documentation for new option: https://packit.dev/docs/configuration/upstream/copr_build#optional-parameters
=> ci: Enable network for Packit build

cmd/yggd/main.go, dist/srpm/yggdrasil.spec.in, internal/constants/constants.go, meson.build, meson_options.txt
By way of a new build option, default_facts_file, enable a compile-time default value for the facts-file flag. The RPMs built out of `dist/srpm` are updated to build with this value set to /var/lib/yggdrasil/canonical-facts.json.
To verify this behavior, make sure that the line defining `facts-file` is removed or commented out from your config file (`/etc/yggdrasil/config.toml`). Running `yggdrasil.service` from this branch on a fully registered system should still find the file `/var/lib/yggdrasil/canonical-facts.json`.
If you connect your yggdrasil to a local broker, you can subscribe to its topics and confirm that facts are still published in the "connection-status" message. Otherwise, connecting your yggdrasil to connect.cloud.stage.redhat.com means you'll have to either scour Kibana …
=> Enable compile-time default facts file

cmd/yggctl/main.go, cmd/yggd/client.go, cmd/yggd/flag.go, cmd/yggd/main.go, go.mod, go.sum, internal/config/config.go, internal/http/client.go, internal/messagejournal/messagejournal.go, internal/tags/tags.go, internal/transport/http.go, internal/transport/mqtt.go, internal/work/dispatcher.go, worker/echo/main.go, worker/worker.go
* Trying to get go-log module from [git.sr.ht/~spc/go-log](https://git.sr.ht/~spc/go-log) started to be terminated with 403 error yesterday
* For this reason we decided to use existing Link's copy on GitHub, because this server should be more reliable. Link is the main author of go-log
* TODO: Really change yggdrasil to use log/slog
=> fix: Stop using git.sr.ht/~spc/go-log and use copy on github.com

.github/workflows/go.yml
Potential fix for [https://github.com/RedHatInsights/yggdrasil/security/code-scanning/5](https://github.com/RedHatInsights/yggdrasil/security/code-scanning/5)
To fix the issue, we will add a `permissions` block at the root level of the workflow. This block will specify `contents: read`, which is sufficient for the operations performed in this workflow. This change ensures that the workflow adheres to the principle of least privilege by restricting the `GITHUB_TOKEN` to read-only access to repository contents.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 5: Workflow does not contain permissions

cmd/yggctl/templates.go
There is a typo in service name com.redhat.Yggdrasil1.Worker1.{{ .Name }}.**S**ervice
=> fix: fixing typo in service name in yggctl template

go.mod
* Card ID: RHEL-100953
* Update go version to 1.24 for default post-quantum X25519MLKEM768 key exchange.
=> build: update go version to 1.24 in go.mod

integration-tests/test_local_privilege_escalation.py
Verifies that unprivileged users cannot abuse com.redhat.Yggdrasil.Dispatch() DBus method to escalate privileges via workers.
* Card id: CCT-1460
=> test: Add integration test for local privilege escalation vulnerability

integration-tests/requirements.txt, integration-tests/test_echo_worker.py, integration-tests/test_yggdrasil_default_facts_file.py, integration-tests/utils.py
This integration test verifies that Yggdrasil publishes facts using default facts file when facts-file is not defined in config.
Also moved  'get_yggdrasil_client_id()' to utils.py so that other tests can use it.
=> test: verify Yggdrasil publishes canonical facts without defined facts-file
