cmd/ygg/main.go, cmd/ygg/status.go
Signed-off-by: Jeremy Crafts <jcrafts@redhat.com>
=> feat: implement ygg status

Makefile, yggdrasil.spec.rpkg
=> build: install /usr/libexec/$LONGNAME

.github/workflows/lint.yml
First attempt at creating a GitHub Action to lint commit messages.
=> Add GitHub Actions to lint code and commits

cmd/yggd/main.go, message_router.go
A race condition exists (related to those occasional "Not Connected" message printed in logs) between the worker registration and the MQTT client connection. The current startup logic forces the MQTT client connection to wait until workers have been spawned and registered. When a worker registers, it triggers a publish of an updated "ConnectionStatus" message. If a worker registers and triggers this publish before the MQTT client has been connected, the ConnectionStatus publish will fail (and the error it returns is "Not Connected").
This PR changes the logic by removing ConnectClient from the all-in-one MessageRouter startup method ConnectPublishStatusAndSubscribe. Instead, ConnectClient is called as soon as the message_router goroutine starts. The ConnectClient method emits a …
=> fix: Ensure connection before publish

HACKING.md
Signed-off-by: Adam Miller <admiller@redhat.com>
=> update HACKING.md to include dep list info

cmd/yggd/main.go, dispatcher.go, message_router.go, yggdrasil.spec.rpkg
Improvements to the MQTT client code, including better logic to connect and subscribe. Also includes rudimentary client reconnects in the event of an unexpected disconnect.
=> MQTT connection hardening

cmd/ygg/register.go
Before registering with RHSM, if the --server argument contains a value, the com.redhat.RHSM1.Config interface is called to set the server.hostname value. This should enable registering to alternative RHSM hosts (for example, Satellite).
Fixes RHCLOUD-13224
=> feat: configure rhsm.conf

HACKING.md, cmd/yggctl/main.go
Includes two message generation commands to generate data and control
messages.
=> feat: add yggctl command

.github/workflows/lint.yml
=> ci: add woke action

cmd/yggd/config.go, cmd/yggd/grpc.go, cmd/yggd/main.go, internal/transport/http.go, internal/transport/mqtt.go, internal/transport/transporter.go
Similar to https://github.com/RedHatInsights/yggdrasil/pull/58, but in this case using different packages, different commits, and different structures. 
Each commit should explain what it's changing.
=> TLS: Renew connection if client certificates changes

cmd/yggd/main.go
Fixes: https://github.com/RedHatInsights/yggdrasil/issues/75
Signed-off-by: Ondra Machacek <omachace@redhat.com>
=> Allow load client-id also from config file

CONTRIBUTING.md, README.md, cmd/yggd/client.go, cmd/yggd/main.go, data/dbus/com.redhat.Yggdrasil1.service.in, data/dbus/com.redhat.yggdrasil.Dispatcher1.service.in, data/dbus/meson.build, data/dbus/yggd.conf, data/systemd/meson.build, data/systemd/yggdrasil.service.in, data/systemd/yggdrasil@.service.in, dbus/com.redhat.Yggdrasil1.xml, dbus/dbus.go, dbus/meson.build, doc/meson.build, go.mod, go.sum, internal/config/config.go, internal/constants/constants.go, internal/work/dispatcher.go, meson.build, meson_options.txt, worker/echo/README.md, worker/echo/com.redhat.yggdrasil.Worker1.echo.service.in, worker/echo/main.go, worker/echo/meson.build, worker/worker.go
Refactor the D-Bus startup logic to account for both dispatcher/worker
interfaces and a "public" com.redhat.Yggdrasil1 interface.
Fixes: #110
=> Public-dbus

worker/echo/main.go
When applied this commit will add a new flag to the echo worker, making it possible to create a slow worker. 
This flag will make the worker to sleep between it receives a message and echoes it.  If the sleep time is not specified it acts as the usual echo worker. 
```sh
[ahitacat@localhost yggdrasil]  go run ./worker/echo --log-level trace --sleep 40s
2023/04/06 14:06:52 addr = echo
2023/04/06 14:06:52 id = ca748f81-2653-4c52-b42b-68793c73d4ca
2023/04/06 14:06:52 responseTo = 
2023/04/06 14:06:52 metadata = map[string]string{}
2023/04/06 14:06:52 data = [104 101 108 108 111]
2023/04/06 14:06:52 emitting event BEGIN
2023/04/06 14:06:52 emitting event WORKING
2023/04/06 14:06:52 sleeping: 40s
2023/04/06 14:07:32 responseCode = 0
2023/04/06 14:07:32 responseMetadata = map[string]string{} …
```
=> Added a sleep flag to echo worker

CONTRIBUTING.md
* Add another section about environment variable MQTT_DEBUG
=> feat: Add information about debugging MQTT trafic

internal/work/dispatcher.go
* When worker works in remote-content mode and address is set to some URL, then the Transmit function should return values according to result of HTTP request POST
=> fix: Return proper values, when worker is in remote-content mode

cmd/yggd/main.go, internal/config/config.go, internal/constants/constants.go
* Converted one huge function into several functions.
* The functionality should be almost the same.
=> feat: refactored yggd main action.

worker/echo/main.go
* Set fields of transmitted messages properly in echo worker
* This commit should fix issue #136
Fixes: #136
=> fix: Set properly messageID and responseTo in echo worker

data/systemd/yggdrasil.service.in, data/systemd/yggdrasil@.service.in
I'll admit I haven't tried this out yet and I have difficulty overseeing all implications. Consider this an RFC with a concrete suggestion on how to implement it.
=> Use systemd PrivateTmp=yes sandboxing

cmd/yggctl/generate.go, cmd/yggctl/generate_test.go, cmd/yggd/client.go, cmd/yggd/main.go, internal/config/tls.go, internal/sync/mutex_map_test.go, internal/transport/http.go, internal/transport/http_test.go, internal/transport/mqtt.go, internal/transport/noop.go, internal/transport/transporter.go, internal/work/dispatcher.go, internal/work/dispatcher_test.go, worker/worker.go
Wrap long lines into multiline formatting using golines.
=> style: format all files with golines

worker/echo/main.go
This commit adds a loop flag to transmit multiple time the echo worker output. By default this flag is 1.
With this flag an user can specified how many messages the echo worker should send.
=> feat: add loop flag to worker

cmd/yggd/main.go
Add a hidden --mqtt-reconnect-delay flag that will sleep for the given
duration before reconnecting to the broker.
=> Add --mqtt-reconnect-delay flag

Makefile
=> Release 0.2.3

HACKING.md
* Some instructions were wrong and it did not work with the latest version of yggdrasil-0.2
=> fix: Update instruction for hacking yggdrasil-0.2

meson.build
Set the version to 0.4.2 to ready 0.4.2 for release.
=> Set version to 0.4.2

cmd/yggctl/actions.go
Card ID" CCT-863
Hyphenated worker names were introduced to satisfy a console-dot assumption that worker names were hyphenated, after which the "yggctl workers list" command was showing both the "legacy" and hyphenated  worker names. Since hyphens in worker names are disallowed by the D-Bus naming policy it is safe to omit any worker names with hyphens when listing them.
=> fix: yggctl list workers should only show legacy names.

cmd/yggd/main.go
If the facts file does not exists upon start, it can’t be watched for changes even if created later. An empty facts dictionary is thus saved if non-existent path is provided.
Card IDs:
* [CCT-861](https://issues.redhat.com/browse/CCT-861)
=> feat: Create facts file if not exists

worker/echo/main.go
Document the reason for emitting the "WORKING" event.
=> doc(echo): Add comment to EmitEvent

.github/workflows/update-version.yml
Include a link to view changes since the last version in the PR description.
Card ID: [CCT-1088](https://issues.redhat.com/browse/CCT-1088)
=> ci: Include link to changes in PR description

cmd/yggd/client.go, doc/diagrams/README.md, doc/yggd.md, internal/transport/noop.go, internal/transport/transporter.go
- Add a document detailing how data flows through yggd.
- Expand on a few existing package and type documentation comments.
Card ID: [CCT-1218](https://issues.redhat.com/browse/CCT-1218)
=> Add a document describing yggd's internals

cmd/yggd/worker.go
=> fix: Avoid returning error when stopping a worker

go.mod
=> build: set go version to 1.22.0

cmd/yggctl/actions.go, internal/transport/http.go, internal/transport/http_test.go
* Do not ignore errors returned by `Close()`, `Fprintf()` and `Fprint() methods
* Do not call defer in loop
* Small fix in one unit test
=> Fixed several lint isssue

.packit.yaml, Makefile
Need to bump the version as part of addressing
Card CCT-1253
Proxy regression issue - Patching/Backports
=> build: Update Makefile to version 0.2.7

cmd/yggd/main.go
* Card ID: CCT-1448
* When the protocol flag is unset, i.e in /etc/yggdrasil/config.toml, it will be inferred from the first server entry (if set)
=> feat: infer protocol from first server entry when unset
